### ISSUE TITLE
Calming Whisper upgrade for Animal Bond gives free stamina

### ISSUE THREAD

**Issue by isavegas** [TorannD/TMagic#12]
From the description, it appears that the `Calming Whisper` upgrade for the `Animal Bond` ability is intended to reduce the static 30 stamina maintenance cost per bond by 15% of the cost itself, resulting in costs of `25.5` for level 1, `21` for level 2, and `16.5` for level 3 of the upgrade. It appears that it instead reduces the maintenance cost by a flat 15 stamina, resulting in 15 stamina being added to your pool for each bond you have.

**Comment by TorannD** [comment]
Fixed!
