### ISSUE TITLE
Summon Minion projectiles aren't cleaned up

### ISSUE THREAD

**Issue by arznaar** [TorannD/TMagic#15]
What's happening:

Game running VERY slow. Basically, speed 1 and 4 are the same. Logger are full of similar errors.

Error log:
```
Exception ticking Projectile_SummonMinion343880 (at (0, 0, 0)): System.NullReferenceException: Object reference not set to an instance of an object
  at TorannMagic.Projectile_SummonMinion.Impact (Verse.Thing hitThing) [0x00000] in <filename unknown>:0 
  at AbilityUser.Projectile_AbilityBase.ImpactSomething () [0x00000] in <filename unknown>:0 
  at AbilityUser.Projectile_AbilityBase.Tick () [0x00000] in <filename unknown>:0 
  at TorannMagic.Projectile_SummonMinion.Tick () [0x00000] in <filename unknown>:0 
  at Verse.TickList.Tick () [0x00000] in <filename unknown>:0 
Verse.Log:Error(String, Boolean)
Verse.TickList:Tick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:UpdatePlay()
Verse.Root_Play:Update()
```

Mods:
- Hardcore_SK
- Jecstools
- A RimWorld of Magic (1.0 from steam)

**Workaround:**
1. Use dev tools to kill your pawn
2. Open save file and replace multyline regexp with empty line:
`[\n\t]+<thing Class="TorannMagic.Projectile_SummonMinion">[<>\/\n\t\w\-\(\),\d\s="]+?</thing>`
(global search from vscode works great)
I had more than 2000 such projectiles.
3. Load save and resurrect the pawn back

PS I don't think this is something that can be fixed by mod author and it can be caused by other mod (HSK has a lot of them). But having this issue in github story can help people.

**Comment by arznaar** [comment]
It there is no way to cleanup such things in mod code - it's fine to close this issue

**Comment by TorannD** [comment]
Fixed bug in update!
