### ISSUE TITLE
DesiredPowerOutput = Traverse.Create...

### ISSUE THREAD

**Issue by cseelhoff** [TorannD/TMagic#25]
https://github.com/TorannD/TMagic/blob/e453e24a4cd7106402508e3a6c584b2b17e204e4/Source/TMagic/TMagic/HarmonyPatches.cs#L1867

Is this line being used?
`float DesiredPowerOutput = Traverse.Create(root: __instance).Field(name: "DesiredPowerOutput").GetValue<float>();`

If not, could it be removed? For whatever reason, "Traverse.Create" creates problems with RimThreaded. If it does indeed need to be used, could it be replaced with something like this? 

`public static FieldRef<CompPowerPlant, float> DesiredPowerOutput= FieldRefAccess<CompPowerPlant, float>("DesiredPowerOutput"); `

I think "FieldRefAccess" is supposed to be more performant too, based on my discussions with the Harmony author

**Comment by TorannD** [comment]
Line removed.
